name: desktop_pet
description: "Add a desktop pet to your Windows and Android."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_riverpod: ^3.3.1
  mmkv: ^2.4.0
  plugin_platform_interface: ^2.0.0
  window_manager: ^0.5.2
  screen_retriever: ^0.2.2
  system_tray: ^2.0.0
  path_provider: ^2.1.0
  archive: ^4.0.9
  file_picker: ^11.0.2
  win32: ^5.0.0
  ffi: ^2.0.0
  desktop_multi_window: ^0.3.0
  flutter_alone: ^4.1.0
  audioplayers: ^6.1.0
  styled_widget: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/default_skin/
    - assets/app_icon.ico
    - assets/default_skin/drag/
    - assets/default_skin/eat/
    - assets/default_skin/happy/
    - assets/default_skin/idle/
    - assets/default_skin/sleep/
    - assets/default_skin/walk/
  generate: true # 务必开启此选项，以启用代码生成器
