name: desktop_pet
description: "Add a desktop pet to your Windows and Android."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # 添加Flutter官方提供的本地化包
    sdk: flutter
  intl: ^0.20.2 # 添加intl包用于格式化和代码生成
  flutter_riverpod: ^2.4.0
  mmkv: ^2.4.0
  plugin_platform_interface: ^2.0.0
  window_manager: ^0.3.0
  flutter_gesture_zone: ^0.1.0
  screen_retriever: ^0.1.0
  system_tray: ^2.0.0
  path_provider: ^2.1.0
  logger: ^1.4.0
  archive: ^3.6.1
  file_picker: ^8.0.0
  image: ^4.2.0
  hotkey_manager: ^0.1.3
  ffi: ^2.0.0
  desktop_multi_window: ^0.3.0
  audioplayers: ^6.1.0
  cupertino_icons: ^1.0.8
  styled_widget: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/default_skin/
    - assets/app_icon.ico
    - assets/default_skin/drag/
    - assets/default_skin/eat/
    - assets/default_skin/happy/
    - assets/default_skin/idle/
    - assets/default_skin/sleep/
    - assets/default_skin/walk/
  generate: true # 务必开启此选项，以启用代码生成器
